// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cleanup() {
  return window['go']['main']['App']['Cleanup']();
}

export function GetAppMode() {
  return window['go']['main']['App']['GetAppMode']();
}

export function GetLogPort() {
  return window['go']['main']['App']['GetLogPort']();
}

export function GetPrinters() {
  return window['go']['main']['App']['GetPrinters']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetUsageGuide() {
  return window['go']['main']['App']['GetUsageGuide']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function Restart() {
  return window['go']['main']['App']['Restart']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ShowHelp() {
  return window['go']['main']['App']['ShowHelp']();
}

export function ShowLogs() {
  return window['go']['main']['App']['ShowLogs']();
}

export function ShowSettings() {
  return window['go']['main']['App']['ShowSettings']();
}

export function StartServer(arg1, arg2) {
  return window['go']['main']['App']['StartServer'](arg1, arg2);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
