// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {menu} from '../models';
import {main} from '../models';

export function Cleanup():Promise<void>;

export function CreateMenu(arg1:string):Promise<menu.Menu>;

export function GetAppMode():Promise<string>;

export function GetLogPort():Promise<number>;

export function GetPrinters():Promise<Array<main.PrinterInfo>>;

export function GetSettings():Promise<main.AppSettings>;

export function GetUsageGuide():Promise<string>;

export function Quit():Promise<void>;

export function Reload():Promise<void>;

export function Restart():Promise<void>;

export function SaveSettings(arg1:main.AppSettings):Promise<void>;

export function ShowHelp():Promise<void>;

export function ShowLogs():Promise<void>;

export function ShowSettings():Promise<void>;

export function StartServer(arg1:string,arg2:string):Promise<void>;

export function StopServer():Promise<void>;

export function UpdateUI(arg1:string):Promise<void>;
